# Generated by Django 6.0.2 on 2026-03-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_member_join_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
