# Generated by Django 6.0.2 on 2026-03-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_member_address_member_email_member_file_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, default='RINKU.jpg', null=True, upload_to='images/'),
        ),
    ]
